spring:
  application:
    name: land-parcel-service
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
      enabled: true

server:
  error:
    include-message: always